# -*- coding: utf-8 -*-
"""Writes the palette CSS into both artboards, and swaps every literal
surface colour for the token that now owns it. Idempotent: run it again
after editing tools/palette.py and it replaces its own previous output."""
import io, re, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palette import PALETTES, ORDER, SEEDS, SPACINGS, CHARACTER, DERIVE

HERE = os.path.dirname(os.path.abspath(__file__)) + '/..'

BEGIN = '    /* >>> palette (generated by tools/build-palette.py) */'
END   = '    /* <<< palette */'

def css():
    """The twelve are seven numbers each, not sixteen colours each.

    Interpolating colour to colour is what forced the old wheel ordering.
    Chrome fades registered colours through sRGB, so emerald to magenta
    passed through rgb(74,73,53), a grey-olive. Keeping every fade short
    avoided the mud, and made every palette look like the one before it.

    Rotating the hue instead means a long change sweeps around the wheel
    rather than across the middle of it, and stays saturated the whole way.
    That is what lets the twelve be ordered for difference.
    """
    first = SEEDS[0]
    fB, fC, fD = SPACINGS[first[2]]
    fk = CHARACTER[first[3]]
    reg = [('hue', '<angle>', '%ddeg' % first[1]),
           ('oB', '<angle>', '%ddeg' % fB), ('oC', '<angle>', '%ddeg' % fC),
           ('oD', '<angle>', '%ddeg' % fD),
           ('aC', '<number>', '%.3f' % fk['aC']),
           ('tC', '<number>', '%.3f' % fk['tC']),
           ('nC', '<number>', '%.2f' % fk['nC'])]

    L = [BEGIN,
         '    /* Twelve palettes. Each one is a hue, three offsets and three',
         '       chroma weights; every colour on the page except the text greys',
         '       derives from those seven. Generated: edit tools/palette.py. */']
    for n, syn, init in reg:
        L.append("    @property --%s { syntax: '%s'; inherits: true; initial-value: %s; }" % (n, syn, init))
    L.append('    :root {')
    for n, _, init in reg:
        L.append('      --%s: %s;' % (n, init))
    L.append('      --hA: var(--hue);')
    L.append('      --hB: calc(var(--hue) + var(--oB));')
    L.append('      --hC: calc(var(--hue) + var(--oC));')
    L.append('      --hD: calc(var(--hue) + var(--oD));')
    for tok in ORDER:
        l, c, h = DERIVE[tok]
        L.append('      --%s: oklch(%s%% %s %s);' % (tok, l, c, h))
    L.append('      transition: ' + ',\n                  '.join(
        '--%s 1.8s cubic-bezier(.45,.05,.35,1)' % n for n, _, _ in reg) + ';')
    L.append('    }')
    for n, (name, seed, sp, ch) in enumerate(SEEDS):
        oB, oC, oD = SPACINGS[sp]
        k = CHARACTER[ch]
        L.append('    /* %2d %-10s %-8s %-8s seed %3d */' % (n, name, sp, ch, seed))
        L.append('    :root[data-pal="%d"] { --oB: %ddeg; --oC: %ddeg; --oD: %ddeg;'
                 ' --aC: %.3f; --tC: %.3f; --nC: %.2f; }'
                 % (n, oB, oC, oD, k['aC'], k['tC'], k['nC']))
    L.append('    .accs { color: var(--accent); }')
    L.append('    .accd { color: var(--tone-d); }')
    L.append('    @media (prefers-reduced-motion: reduce) { :root { transition: none; } }')
    L.append(END)
    return '\n'.join(L) + '\n'

SHADOW = lambda m: 'color-mix(in srgb, var(--shadow) %d%%, transparent)' % round(float(m.group(1)) * 100)

SWAPS = [
    (r'background: radial-gradient\(closest-side, color-mix\(in srgb, var\(--(\w[\w-]*)\) (\d+)%, transparent\), transparent\);',
     r'background: radial-gradient(closest-side, color-mix(in srgb, var(--\1) \2%, transparent), transparent);'),
    (r'(background(?:-color)?:\s*)#FFFFFF', r'\1var(--card)'),
    (r'#F7F8FC', 'var(--ground)'),
    (r'#F1F2F8', 'var(--surface)'),
    (r'#ECEDF4|#ECEDF5', 'var(--surface-2)'),
    (r'#F0F1F7|#E7E8F2', 'var(--line)'),
    (r'rgba\(21,\s*22,\s*43,\s*(\.\d+)\)', SHADOW),
    (r'rgba\(247,\s*248,\s*252,\s*0\.78\)', 'color-mix(in srgb, var(--ground) 78%, transparent)'),
    (r'rgba\(247,\s*248,\s*252,\s*0\)', 'transparent'),
    # two greys that fail AA on any surface; the ramp tightens, but all three pass
    (r'rgba\(255,\s*255,\s*255,\s*0\.55\)', 'var(--card)'),
    (r'#7A7B92', '#5E5E6E'),
    (r'#9C9DB0', '#676877'),
]

def main():
    block = css()
    for f in ('Main.dc.html', 'phone.shell.html'):
        path = HERE + '/' + f
        s = io.open(path, encoding='utf-8').read()
        i = s.find('<script data-dc-script')
        body, tail = (s[:i], s[i:]) if i > 0 else (s, '')

        if BEGIN in body:
            body = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n', block, body, flags=re.S)
        else:
            m = re.search(r'    /\* One angle drives the page.*?prefers-reduced-motion: reduce\) \{ :root \{ transition: none; \} \}\n',
                          body, re.S)
            if not m:
                sys.exit('no palette block and no hue block to replace in ' + f)
            body = body[:m.start()] + block + body[m.end():]

        # swap everywhere except inside the generated block itself, which is
        # the one place literal hex is the point
        pre, rest = body.split(BEGIN, 1)
        block_body, post = rest.split(END, 1)
        for pat, rep in SWAPS:
            pre = re.sub(pat, rep, pre)
            post = re.sub(pat, rep, post)
            tail = re.sub(pat, rep, tail)          # renderVals lives in here
        io.open(path, 'w', encoding='utf-8').write(
            pre + BEGIN + block_body + END + post + tail)
        print('  %-18s palette written, literals swapped' % f)

if __name__ == '__main__':
    main()
