# -*- coding: utf-8 -*-
"""Writes the palette CSS into both artboards, and swaps every literal
surface colour for the token that now owns it. Idempotent: run it again
after editing tools/palette.py and it replaces its own previous output."""
import io, re, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palette import PALETTES, ORDER

HERE = os.path.dirname(os.path.abspath(__file__)) + '/..'

BEGIN = '    /* >>> palette (generated by tools/build-palette.py) */'
END   = '    /* <<< palette */'

def css():
    L = [BEGIN,
         '    /* Every colour on the page except the text greys lives here. Eight',
         '       combinations, one switch: setting data-pal on <html> repaints the',
         '       lot. Each token is registered so it interpolates rather than',
         '       snapping, which is what makes the change read as a fade.',
         '       Generated: edit tools/palette.py, not this block. */']
    for t in ORDER:
        L.append("    @property --%s { syntax: '<color>'; inherits: true; initial-value: %s; }"
                 % (t, PALETTES[0][1][t]))
    L.append('    :root {')
    L.append('      transition: ' + ',\n                  '.join('--%s 2.4s cubic-bezier(.45,.05,.35,1)' % t for t in ORDER) + ';')
    L.append('    }')
    for n, (name, p) in enumerate(PALETTES):
        L.append('    /* %d %s */' % (n, name))
        L.append('    :root, :root[data-pal="%d"] {' % n if n == 0 else '    :root[data-pal="%d"] {' % n)
        for t in ORDER:
            L.append('      --%s: %s;' % (t, p[t]))
        L.append('    }')
    L.append('    .accs { color: var(--accent); }')
    L.append('    .accd { color: var(--tone-d); }')
    L.append('    @media (prefers-reduced-motion: reduce) { :root { transition: none; } }')
    L.append(END)
    return '\n'.join(L) + '\n'

SHADOW = lambda m: 'color-mix(in srgb, var(--shadow) %d%%, transparent)' % round(float(m.group(1)) * 100)

SWAPS = [
    (r'background: radial-gradient\(closest-side, color-mix\(in srgb, var\(--(\w[\w-]*)\) (\d+)%, transparent\), transparent\);',
     r'background: radial-gradient(closest-side, color-mix(in srgb, var(--\1) \2%, transparent), transparent);'),
    (r'(background(?:-color)?:\s*)#FFFFFF', r'\1var(--card)'),
    (r'#F7F8FC', 'var(--ground)'),
    (r'#F1F2F8', 'var(--surface)'),
    (r'#ECEDF4|#ECEDF5', 'var(--surface-2)'),
    (r'#F0F1F7|#E7E8F2', 'var(--line)'),
    (r'rgba\(21,\s*22,\s*43,\s*(\.\d+)\)', SHADOW),
    (r'rgba\(247,\s*248,\s*252,\s*0\.78\)', 'color-mix(in srgb, var(--ground) 78%, transparent)'),
    (r'rgba\(247,\s*248,\s*252,\s*0\)', 'transparent'),
    # two greys that fail AA on any surface; the ramp tightens, but all three pass
    (r'rgba\(255,\s*255,\s*255,\s*0\.55\)', 'var(--card)'),
    (r'#7A7B92', '#5E5E6E'),
    (r'#9C9DB0', '#676877'),
]

def main():
    block = css()
    for f in ('Main.dc.html', 'phone.shell.html'):
        path = HERE + '/' + f
        s = io.open(path, encoding='utf-8').read()
        i = s.find('<script data-dc-script')
        body, tail = (s[:i], s[i:]) if i > 0 else (s, '')

        if BEGIN in body:
            body = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n', block, body, flags=re.S)
        else:
            m = re.search(r'    /\* One angle drives the page.*?prefers-reduced-motion: reduce\) \{ :root \{ transition: none; \} \}\n',
                          body, re.S)
            if not m:
                sys.exit('no palette block and no hue block to replace in ' + f)
            body = body[:m.start()] + block + body[m.end():]

        # swap everywhere except inside the generated block itself, which is
        # the one place literal hex is the point
        pre, rest = body.split(BEGIN, 1)
        block_body, post = rest.split(END, 1)
        for pat, rep in SWAPS:
            pre = re.sub(pat, rep, pre)
            post = re.sub(pat, rep, post)
            tail = re.sub(pat, rep, tail)          # renderVals lives in here
        io.open(path, 'w', encoding='utf-8').write(
            pre + BEGIN + block_body + END + post + tail)
        print('  %-18s palette written, literals swapped' % f)

if __name__ == '__main__':
    main()
